### ISSUE TITLE
Dependency error with Python versions > 3.10

### ISSUE THREAD

**Issue by metacontext** [ISE-FIZKarlsruhe/fizzysearch#1]
Fizzysearch currently depends on `numpy 1.22.4`. This version of numpy is only compatible to Python versions until 3.10. When trying to install fizzysearch with Python > 3.10, it will fail with errors during installation. The reason being that starting with Python 3.10, `distutils` (on which numpy 1.22.4 depends) is no longer included by default and has been integrated into `setuptools`. Therefore, with newer Python installations, the installation process fails with

`ModuleNotFoundError: No module named 'distutils'`

Solution: Use a newer version of numpy that is compatible with Python > 3.10

**Comment by epoz** [comment]
I had perviously pinned numpy to 1.22.4 because newer versions caused conflicts in some other libraries which didn't support the newer numpy. (I forget which)

Will give it another try, with newer numpy versions. Hopefully those other packages have since also upgraded.
